fixtures-exporting
aviCardStringExport
^
'BEGIN:VCARD' , String crlf ,
'VERSION:3.0' , String crlf ,
'N:Bryant;Avi;;;' , String crlf ,
'FN:Avi Bryant' , String crlf ,
'ADR;TYPE=home;TYPE=pref:;;xxx E. xx Ave;Vancouver;BC;V5V 1E3;Canada' , String crlf ,
'TEL;TYPE=home;TYPE=pref:(778) xxx-xxxx' , String crlf ,
'EMAIL;TYPE=internet;TYPE=pref;TYPE=work:avi@smallthought.com' , String crlf ,
'EMAIL;TYPE=internet;TYPE=home:avi.bryant@gmail.com' , String crlf ,
'TZ:-05:00' , String crlf ,
'X-AIM;TYPE=pref:avbry' , String crlf ,
'X-MSN;TYPE=pref:avi666@hotmail.com' , String crlf ,
'END:VCARD' , String crlf