fixtures-parsing
ericCardString
^
'BEGIN:VCARD' , String crlf ,
'VERSION:3.0' , String crlf ,
'N:Wahlforss;Eric;;;' , String crlf ,
'FN:Eric Wahlforss' , String crlf ,
'TITLE:Entrepreneur / Musician' , String crlf ,
'EMAIL;type=INTERNET;type=WORK;type=pref:eric at wahlforss.com' , String crlf ,
'item1.EMAIL;type=INTERNET:eric at forss.to' , String crlf ,
'item1.X-ABLabel:_$!<Other>!$_' , String crlf ,
'TEL;type=CELL;type=pref:+46703639900' , String crlf ,
'item2.TEL:+491793126620' , String crlf ,
'item2.X-ABLabel:_$!<Other>!$_' , String crlf ,
'item3.ADR;type=HOME;type=pref:;;Tavastgatan 6;Stockholm;;11820;Sweden' , String crlf ,
'item3.X-ABADR:se' , String crlf ,
'URL:http://eric.wahlforss.com/' , String crlf ,
'X-AIM;type=HOME;type=pref:ericwahlforss' , String crlf ,
'X-MSN;type=HOME:ericwahlforss@hotmail.com' , String crlf ,
'X-ICQ;type=WORK;type=pref:5399905' , String crlf ,
'CATEGORY:24HDC' , String crlf ,
'END:VCARD' , String crlf