fixtures-parsing
goofyCardString
^'BEGIN:VCARD' , String crlf ,
'VERSION:2.1' , String crlf ,
'FN;CHARSET=ISO-8859-1:Markus Tschannen' , String crlf ,
'N;CHARSET=ISO-8859-1:Tschannen;Markus;;;'  , String crlf ,
'ADR;TYPE=HOME;CHARSET=ISO-8859-1:;;Neufeldstrasse 11;Bern;;3012;Schweiz' , String crlf ,
'TEL;TYPE=VOICE,HOME;CHARSET=ISO-8859-1:+41 31 302 08 56' , String crlf ,
'TEL;TYPE=CELL,HOME;CHARSET=ISO-8859-1:+41 78 845 24 12' , String crlf ,
'BDAY:1980-10-30' , String crlf ,
'TZ;VALUE=text:-05:00; EST; Raleigh/North America' , String crlf ,
'GEO:37.386013;-122.082932' , String crlf ,
'END:VCARD' , String crlf