fixtures-parsing
josephCardString
^
'begin:vcard' , String crlf ,
'n:THOMAS;JOSEPH' , String crlf ,
'tel;home:3790977' , String crlf ,
'tel;work:2349961,2349972,2349986 EXT:7089' , String crlf ,
'x-mozilla-html:FALSE' , String crlf ,
'url:www.alcatel.com' , String crlf ,
'org:ADCC;VI-32' , String crlf ,
'version:2.1' , String crlf ,
'email;internet:Thomas.Joseph@adcc.alcatel.be' , String crlf ,
'title:SOFTWARE ENGINEER' , String crlf ,
'adr;quoted-printable:;;94/95,Thiru-Vi-Ka Industrial Estate,=0D=0AGuindy,=0D=0A;Chennai;Tamil Nadu;600032;India' , String crlf ,
'note;quoted-printable:=0D=0A=0D=0A=0D=0A=0D=0A=0D=0AMake Life a Meaningful Journey.......=0D=0A=0D=0A' , String crlf ,
'fn:JOSEPH' , String crlf ,
'end:vcard' , String crlf