fixtures-parsing
maeveCardString
^
'BEGIN:VCARD' , String crlf ,
'VERSION:3.0' , String crlf ,
'N:Price;Maeve;;;' , String crlf ,
'FN:Maeve Price' , String crlf ,
'TITLE:Digital Editor' , String crlf ,
'EMAIL;type=INTERNET;type=WORK;type=pref:maeve@zenediting.com' , String crlf ,
'EMAIL;type=INTERNET;type=WORK:maeve.price@myoasis.colum.edu' , String crlf ,
'EMAIL;type=INTERNET;type=HOME:mahaevey@aol.com' , String crlf ,
'TEL;type=CELL;type=pref:312-505-9563' , String crlf ,
'item1.ADR;type=HOME;type=pref:;;1636 W. Pierce Ave #1;Chicago;IL;60622;USA' , String crlf ,
'item1.X-ABADR:us' , String crlf ,
'item2.URL;type=pref:http\://www.zenediting.com' , String crlf ,
'item2.X-ABLabel:_$!<HomePage>!$_' , String crlf ,
'item3.URL:http\://www.myspace.com/maeveprice' , String crlf ,
'item3.X-ABLabel:my space' , String crlf ,
'BDAY;value=date:2005-06-14' , String crlf ,
'X-AIM;type=HOME;type=pref:Mahaevey' , String crlf ,
'X-MSN;type=HOME;type=pref:dgu186@hotmail.com' , String crlf ,
'CATEGORIES:Friends,Columbia College Chicago,Family' , String crlf ,
'X-ABUID:032C4F53-35BA-490E-8C25-5DBA59230358\:ABPerson' , String crlf ,
'END:VCARD' , String crlf