fixtures-parsing
philippeCardString
	^
'BEGIN:VCARD' , String crlf ,
'VERSION:2.1' , String crlf ,
'N;ENCODING=QUOTED-PRINTABLE:Marschall;Philippe' , String crlf ,
'FN:Philippe Marschall' , String crlf ,
'NICKNAME;ENCODING=QUOTED-PRINTABLE:pmm' , String crlf ,
'ADR;HOME;ENCODING=QUOTED-PRINTABLE:;;Poststrasse 1;Z=FCrich;;8001;' , String crlf ,
'EMAIL;INTERNET:philippe.marschall@gmail.com' , String crlf ,
'END:VCARD' , String crlf