fixtures-parsing
seanCardString
^
'BEGIN:VCARD' , String crlf ,
'VERSION:2.1' , String crlf ,
'X-PLAXO-VERSION:1.0' , String crlf ,
'N:Glazier;Sean;;;' , String crlf ,
'FN:Sean Glazier' , String crlf ,
'ORG:Cincom Systems' , String crlf ,
'TITLE:Lead Software Engineer' , String crlf ,
'ADR;WORK;ENCODING=QUOTED-PRINTABLE:;;6 Christie Lane;Stratham;NH;03885;USA' , String crlf ,
'TEL;WORK;VOICE:603 772 4480' , String crlf ,
'TEL;CELL;VOICE:603 770 8260' , String crlf ,
'EMAIL;PREF;INTERNET;WORK:sglazier@comcast.net' , String crlf ,
'X-AIM;WORK:Visualwave' , String crlf ,
'ADR;HOME;ENCODING=QUOTED-PRINTABLE:;;6 Christie Lane;Stratham;NH;03885;USA' , String crlf ,
'TEL;HOME;VOICE:603 772 2852' , String crlf ,
'TEL;CELL;VOICE:603 770 8260' , String crlf ,
'EMAIL;INTERNET;HOME:sglazier@comcast.net' , String crlf ,
'X-AIM;HOME:Visualwave' , String crlf ,
'BDAY:2005-10-01' , String crlf ,
'END:VCARD' , String crlf